### ISSUE TITLE
Variables do not allow underscores in names

### ISSUE THREAD

**Issue by codyben** [mech-lang/mech#2]
**Mech Version:** 3.0.0
**Issue:** Variables fail to parse if an underscore is present.

Example:
In the file below, placing an underscore in the variable name will prevent program execution. When viewing the program using ```mech core``` no variable defintion is found for ```an_underscore```.
```
TestBlock
  #NoSpaces = 5
  #an_underscore = 4

display
  #mech/output = #NoSpaces
```
When no underscore is present, everything works fine. 
```
TestBlock
  #NoSpaces = 5
  #anunderscore = 4

display
  #mech/output = #NoSpaces
```

I'm not sure if this is intended, but I figured I'd open an issue. An open pull request which handles this issue is seen here: [https://github.com/mech-lang/syntax/pull/1](url)

**Comment by cmontella** [comment]
I've decided this is not a bug, as it's strictly preferred to use - instead of _ in names.
