### ISSUE TITLE
Linker error when cross-compiling for non-x86_64 architectures

### ISSUE THREAD

**Issue by pvonmoradi** [mech-lang/mech#6]
I'm [packaging mech-lang](https://github.com/termux/termux-packages/pull/11894) for Termux (Android). When I'm cross-compiling for aarch64, arm or i686, I'm getting the following [linker error](https://github.com/termux/termux-packages/runs/8300471169?check_suite_focus=true) about openssl:
```
  = note: ld: error: /data/data/com.termux/files/usr/lib/libssl.so is incompatible with elf64-x86-64
          ld: error: /data/data/com.termux/files/usr/lib/libcrypto.so is incompatible with elf64-x86-64
          collect2: error: ld returned 1 exit status      

error: could not compile `mech` due to previous error
Error: Process completed with exit code 101.
```

Interesting project, btw! Is it similar to ROS in scope and application domain? Is there literature (papers, etc) on this?

**Comment by cmontella** [comment]
Hi Pooya, sorry I didn't see your issues until recently. Yes, Mech is similarly scoped as ROS. This is the only paper published right now: http://docs.mech-lang.org/#/live2019.mec I'm trying to publish another one at ICRA next year, but we'll see how that goes.

As far as this issue goes, it's a tricky one. Right now, Mech is designed to work for 64-bit operating systems only. We'll have to do more work in the future to get it working on different architectures.
